// <auto-generated />
namespace FilmQZ.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedMissingDefaultValuesForGameEntities : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedMissingDefaultValuesForGameEntities));
        
        string IMigrationMetadata.Id
        {
            get { return "201711251446377_addedMissingDefaultValuesForGameEntities"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
